// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function APIHandler():Promise<http.Handler>;

export function GetAndClearLastNotifiedChat():Promise<string>;

export function GetAppInfo():Promise<Record<string, any>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenImageDialog():Promise<string>;

export function OpenLogDir():Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveWindowSize():Promise<void>;

export function SendFile(arg1:string):Promise<Record<string, string>>;

export function SendFileFromBase64(arg1:string,arg2:string,arg3:string):Promise<Record<string, string>>;

export function SendFilePath(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SendImageBase64(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, string>>;

export function SendImagePath(arg1:string,arg2:string):Promise<Record<string, string>>;

export function SetNotificationAppName(arg1:string):Promise<void>;

export function SetWindowIcon(arg1:string):Promise<void>;

export function SetWindowTheme(arg1:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string,arg3:string):Promise<void>;
