// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIHandler() {
  return window['go']['main']['DesktopApp']['APIHandler']();
}

export function GetAndClearLastNotifiedChat() {
  return window['go']['main']['DesktopApp']['GetAndClearLastNotifiedChat']();
}

export function GetAppInfo() {
  return window['go']['main']['DesktopApp']['GetAppInfo']();
}

export function OpenFile(arg1) {
  return window['go']['main']['DesktopApp']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['DesktopApp']['OpenFileDialog']();
}

export function OpenImageDialog() {
  return window['go']['main']['DesktopApp']['OpenImageDialog']();
}

export function OpenLogDir() {
  return window['go']['main']['DesktopApp']['OpenLogDir']();
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['DesktopApp']['RevealInExplorer'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['DesktopApp']['SaveFileDialog'](arg1);
}

export function SaveWindowSize() {
  return window['go']['main']['DesktopApp']['SaveWindowSize']();
}

export function SendFile(arg1) {
  return window['go']['main']['DesktopApp']['SendFile'](arg1);
}

export function SendFileFromBase64(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['SendFileFromBase64'](arg1, arg2, arg3);
}

export function SendFilePath(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SendFilePath'](arg1, arg2);
}

export function SendImageBase64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['DesktopApp']['SendImageBase64'](arg1, arg2, arg3, arg4);
}

export function SendImagePath(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SendImagePath'](arg1, arg2);
}

export function SetNotificationAppName(arg1) {
  return window['go']['main']['DesktopApp']['SetNotificationAppName'](arg1);
}

export function SetWindowIcon(arg1) {
  return window['go']['main']['DesktopApp']['SetWindowIcon'](arg1);
}

export function SetWindowTheme(arg1) {
  return window['go']['main']['DesktopApp']['SetWindowTheme'](arg1);
}

export function ShowNotification(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ShowNotification'](arg1, arg2, arg3);
}
